#!/bin/bash

# R is for assigning a random number to it
R=0
DIRS=()

# Add message whenever cd into a folder
echo 'message_cd() {
    builtin cd "$@" && { [ ! -f .cd-message ] || cat .cd-message 1>&2; }
}

alias cd=message_cd' >> ~/.bashrc
. ~/.bashrc

for FILE in /home/*; do
    if [[ -d $FILE ]]; then
        DIRS+=( "$FILE" )
        echo $FILE
    fi
done
for studentDIR in "${DIRS[@]}"; do
    # imageLoc is an array used to disperse images to multiple locations that I set up later
    imageLoc=(/$studentDIR/i/b/e/j/l/s/v/ /$studentDIR/i/a/g/kitty/m/q/w/ /$studentDIR/i/c/e/h/k/ /$studentDIR/i/a/e/kitty/ /$studentDIR/i/z/g/j/l/o/w/ /$studentDIR/i/d/f/kitty/k/n/t/)
    imageName=(002edurange.jpg edurange001.gif edurange3.GIF 4edurange.jpeg edurange006weeeeeee.png edurange5meow.JPG)

    # Function to create a random number every time it is called
    random_Number(){
        R=$(($RANDOM%999999))
    }

    # How you call a function in bash. Just type the name lol
    random_Number

    # Making directories and chmoding them for the scenario
    mkdir -p /$studentDIR/followMe/keepGOING/another\ folder\ wee/im.another.folder/WOOT/dontstop/okYouAreHERE\!
    touch /$studentDIR/followMe/keepGOING/another\ folder\ wee/im.another.folder/WOOT/dontstop/okYouAreHERE\!/$R
    mkdir /$studentDIR/stuff
    chmod -R 777 /$studentDIR/followMe/
    chmod -R 777 /$studentDIR/stuff/

    # Moving the files from toLearn into /tmp/toLearn
    mkdir /$studentDIR/toLearn
    cp /tmp/scenario-dungeon-crawler-basics/toLearn/* /$studentDIR/toLearn/
    chmod -R 777 /$studentDIR/toLearn

    # This takes all the files in stuff moves to /tmp/stuff
    cp /tmp/scenario-dungeon-crawler-basics/stuff/* /$studentDIR/stuff/

    random_Number
    echo $R"SUPERSECRET" > /$studentDIR/stuff/imatextfiletoo.txt

    # More setting up for the scenario
    mkdir /$studentDIR/textfiles
    echo "ALERT - This is a message!" > /$studentDIR/textfiles/.cd-message
    echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed ullamcorper nisi. Morbi risus libero, ultricies in condimentum in, porttitor sit amet quam. Curabitur ultrices, magna ut viverra posuere, urna massa molestie ex, at pellentesque magna justo eget arcu. Vestibulum eget ante vulputate, euismod lacus in, lobortis nisl. Suspendisse tempus maximus erat ut consectetur. Donec molestie massa vitae commodo ultricies. Integer dignissim leo consequat nisi sodales, acvolutpat magna
    euismod. Maecenas urna sem, congue et libero nec, viverra condimentum ante. Praesent bibendum nulla ut sapien volutpat tincidunt. Sed sed nibh id ante maximus dignissim. Sed congue egestas lacinia. Duis non finibus arcu, a viverra mauris. Nunc ac felis ac turpis congue faucibus." > /$studentDIR/textfiles/one.txt
    echo "7625837645734265487236549367527365827634587623485763982576489237645832765489762385497632" > /$studentDIR/textfiles/two.txt
    echo -e "Fighting evil by moonlight\nWinning love by daylight\nNever running from a real fight\nShe is the one named Sailor Moon\nShe will never turn her back on a friend\nShe is always there to defend\nShe is the one on whom we depend" > /$studentDIR/textfiles/three.txt
    chmod -R 777 /$studentDIR/textfiles
    mkdir /$studentDIR/editme
    echo -e "Line 1\nLine 2\nLine 3\nLine 4\nLine 5" > /$studentDIR/editme/editme.txt
    chmod -R 777 /$studentDIR/editme

    # This is a nifty way to create multiple folders all at once :3
    mkdir -p /$studentDIR/i/{a,b,c,d,z,y,x}/{e,f,g}/{h,kitty,j}/{k,l,m}/{n,o,p,q,r,s}/{t,u,v,w}

    # Counter is used for the following for loop. Taking each image in the folder images and moving them to a new location
    counter=0
    for filename in /tmp/scenario-dungeon-crawler-basics/images/*;
    do
        cp $filename ${imageLoc[$counter]}${imageName[$counter]}
        counter=$((counter+1))
    done

    chmod -R 777 /$studentDIR/i

    # Final Mission setup
    cp /tmp/scenario-dungeon-crawler-basics/final-mission/U348bdks8cowFJS8dJF3hHDFj.jpg /$studentDIR/i/y/f/kitty/k/r/u/U348bdks8cowFJS8dJF3hHDFj.jpg
    cp /tmp/scenario-dungeon-crawler-basics/final-mission/.donthackme /$studentDIR/i/y/f/kitty/k/r/u/.donthackme
    chmod -R 777 /$studentDIR/i/y/f/kitty/k/r/u/*
    mkdir /$studentDIR/final-mission
    chmod 777 /$studentDIR/final-mission
done
rm -r /tmp/scenario-dungeon-crawler-basics
